### ISSUE TITLE
Devices 

### ISSUE THREAD

**Issue by potapovDim** [browserstack/nightwatch-browserstack#6]
how to add devices ?

**Comment by vedharish** [comment]
Hey @potapovDim , you can add the device name in the desiredCapabilities object.

Example - [add here](https://github.com/browserstack/nightwatch-browserstack/blob/481851cdb641601a8ba8307712c0d5c2b76fdcc8/conf/single.conf.js#L17)

```
desiredCapabilities: {
        'build': 'nightwatch-browserstack',
        'browserstack.user': process.env.BROWSERSTACK_USERNAME || 'BROWSERSTACK_USERNAME',
        'browserstack.key': process.env.BROWSERSTACK_ACCESS_KEY || 'BROWSERSTACK_ACCESS_KEY',
        'browserstack.debug': true,
        'browserName' : 'android',
        'platform' : 'ANDROID',
        'device' : 'Samsung Galaxy Note 3'
}
```

You can auto-generate these capabilities from [here](https://www.browserstack.com/automate/node#setting-os-and-browser)

**Comment by potapovDim** [comment]
Hey @vedharish  ,how can i do multi desiredCapabilities??
if i want to run my test on 10 devices ??

**Comment by vedharish** [comment]
@potapovDim you will need to add the capabilities in `conf/parallel.conf.js` and then run `npm run parallel`. Please have a look at `README.md`

**Comment by ganlanyuan** [comment]
How can I add the `desiredCapabilities` or where can I find it on the website?
For example:
```js
ie: {
  desiredCapabilities: {
    browser: "internet explorer",
    version: "8",
    platform: "Windows 7 (64-bit)",
  }
}
```
Is this correct?
Thanks

**Comment by ganlanyuan** [comment]
Just found out. thanks
