### ISSUE TITLE
Can I run local tests in parallel, or am I confused?

### ISSUE THREAD

**Issue by dwoodwardgb** [browserstack/nightwatch-browserstack#7]
In the example for browserstack local there is a global `beforeEach()` and `afterEach()` that setup and teardown the browserstack local server for each test. Why is this necessary for each test? Why can't there just be one server instance for all the tests? The reason I ask is because I'm trying to run parallel tests locally and one runs fine but the other complains with this error: `LocalError: Either another browserstack local client is running on your machine or some server is listening on port 45691`.

**Comment by tr4n2uil** [comment]
Thanks for that! Updated sample in PR #8

**Comment by vedharish** [comment]
@dwoodwardgb You can now run `npm run parallel_local` to run local tests in parallel. Please have a look at [the runner script](https://github.com/browserstack/nightwatch-browserstack/blob/master/scripts/local.runner.js)

**Comment by dwoodwardgb** [comment]
Thanks!

**Comment by StephanBijzitter** [comment]
@vedharish using the local parallel config, if I specify one browser, everything is fine. But when I started adding more browsers, child processes are spawned and then nothing really happens. The command exits after a few seconds (no error) and browserstack hasn't received any data. Adding `--verbose` also doesn't really do anything.

**Comment by irobayna** [comment]
Same here, parallel with multiple browsers does not work
